feat(config): 优化本地开发配置和日志记录

diff --git a/cron/cron.hourly/run_hourly b/cron/cron.hourly/run_hourly
--- a/cron/cron.hourly/run_hourly
+++ b/cron/cron.hourly/run_hourly
@@ -1,7 +1,19 @@
 #!/bin/sh
 
+LOG_DIR=/data/logs
+LOG_FILE=${LOG_DIR}/cron.log
+mkdir -p ${LOG_DIR}
+
+START=$(date '+%Y-%m-%d %H:%M:%S')
+echo "[${START}] [hourly] basic_data_daily_job START" >> ${LOG_FILE}
+
 cd /data/InStock
-exec uv run --frozen instock-job basic_data_daily_job
-#mkdir -p /data/logs
-#DATE=`date +%Y-%m-%d:%H:%M:%S`
-#echo $DATE >> /data/logs/hourly.log
+uv run --frozen instock-job basic_data_daily_job >> ${LOG_FILE} 2>&1
+EXIT_CODE=$?
+
+END=$(date '+%Y-%m-%d %H:%M:%S')
+if [ ${EXIT_CODE} -eq 0 ]; then
+    echo "[${END}] [hourly] basic_data_daily_job END (success, started at ${START})" >> ${LOG_FILE}
+else
+    echo "[${END}] [hourly] basic_data_daily_job FAILED (exit_code=${EXIT_CODE}, started at ${START})" >> ${LOG_FILE}
+fi
diff --git a/cron/cron.monthly/run_monthly b/cron/cron.monthly/run_monthly
--- a/cron/cron.monthly/run_monthly
+++ b/cron/cron.monthly/run_monthly
@@ -1,14 +1,18 @@
 #!/bin/sh
 
-#清除缓存数据
-rm -rf /data/InStock/instock/cache/hist/*
-#MONTH=`date -d '' +%Y%m`
-#cd /data/InStock/instock/cache/hist && rm -rf !(${MONTH})
-#DATE=`date -d '' +%Y-%m-%d`
-#DATE_1=`date -d '-1 days' +%Y-%m-%d`
-#DATE_2=`date -d '-2 days' +%Y-%m-%d`
-#cd /data/InStock/instock/cache/hist/${MONTH} && rm -rf !(${DATE}|${DATE_1}|${DATE_2})
+LOG_DIR=/data/logs
+LOG_FILE=${LOG_DIR}/cron.log
+mkdir -p ${LOG_DIR}
 
-#mkdir -p /data/logs
-#DATE=`date +%Y-%m-%d:%H:%M:%S`
-#echo $DATE >> /data/logs/monthly.log
+START=$(date '+%Y-%m-%d %H:%M:%S')
+echo "[${START}] [monthly] cache cleanup START" >> ${LOG_FILE}
+
+rm -rf /data/InStock/instock/cache/hist/*
+EXIT_CODE=$?
+
+END=$(date '+%Y-%m-%d %H:%M:%S')
+if [ ${EXIT_CODE} -eq 0 ]; then
+    echo "[${END}] [monthly] cache cleanup END (success, started at ${START})" >> ${LOG_FILE}
+else
+    echo "[${END}] [monthly] cache cleanup FAILED (exit_code=${EXIT_CODE}, started at ${START})" >> ${LOG_FILE}
+fi
diff --git a/cron/cron.workdayly/run_workdayly b/cron/cron.workdayly/run_workdayly
--- a/cron/cron.workdayly/run_workdayly
+++ b/cron/cron.workdayly/run_workdayly
@@ -1,8 +1,19 @@
 #!/bin/sh
 
-cd /data/InStock
-exec uv run --frozen instock-job execute_daily_job
+LOG_DIR=/data/logs
+LOG_FILE=${LOG_DIR}/cron.log
+mkdir -p ${LOG_DIR}
 
-#mkdir -p /data/logs
-#DATE=`date +%Y-%m-%d:%H:%M:%S`
-#echo $DATE >> /data/logs/workdayly.log
+START=$(date '+%Y-%m-%d %H:%M:%S')
+echo "[${START}] [workdayly] execute_daily_job START" >> ${LOG_FILE}
+
+cd /data/InStock
+uv run --frozen instock-job execute_daily_job >> ${LOG_FILE} 2>&1
+EXIT_CODE=$?
+
+END=$(date '+%Y-%m-%d %H:%M:%S')
+if [ ${EXIT_CODE} -eq 0 ]; then
+    echo "[${END}] [workdayly] execute_daily_job END (success, started at ${START})" >> ${LOG_FILE}
+else
+    echo "[${END}] [workdayly] execute_daily_job FAILED (exit_code=${EXIT_CODE}, started at ${START})" >> ${LOG_FILE}
+fi
